



@URL = https://tniybkqv34.execute-api.eu-north-1.amazonaws.com


### Get all users
GET {{URL}}/users

### Create a user
POST {{URL}}/users
Content-Type: application/json

{
    "name": "coding addict",
    "email": "coding@addict.com"
}

### Get a user
GET {{URL}}/users/db111588-e747-40c8-84b4-004157332aab

### Update a user
PUT {{URL}}/users/db111588-e747-40c8-84b4-004157332aab
Content-Type: application/json

{
    "name": "coding addict",
    "email": "coding@addict.com"
}

### Delete a user
DELETE {{URL}}/users/7b6da902-c148-4d93-b303-5bc98d2fc7b5
